#!/usr/local/bin/tcsh
#
# ParaGauss, a program package for high-performance computations
# of molecular systems
# Copyright (C) 2014
# T. Belling, T. Grauschopf, S. Krüger, F. Nörtemann, M. Staufer,
# M. Mayer, V. A. Nasluzov, U. Birkenheuer, A. Hu, A. V. Matveev,
# A. V. Shor, M. S. K. Fuchs-Rohr, K. M. Neyman, D. I. Ganyushin,
# T. Kerdcharoen, A. Woiterski, A. B. Gordienko, S. Majumder,
# M. H. i Rotllant, R. Ramakrishnan, G. Dixit, A. Nikodem, T. Soini,
# M. Roderus, N. Rösch
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation [1].
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# [1] http://www.gnu.org/licenses/gpl-2.0.html
#
# Please see the accompanying LICENSE file for further information.
#
# This file serves only as a wrapper to the LRZ-graphik call 'graphik'
# which at the same time will reset the bell to the values originally defined
# by the user.

# find out the bell settings of the dear user
if (-e bimmel ) then
  echo " **** removing file bimmel ****"
  rm bimmel
endif
xset -q | grep 'bell' >> bimmel
set bimstat=$status

graphik $1 $2
 

set vol=`awk '{print $3}' bimmel`
set pitch=`awk '{print $6}' bimmel`
set dur=`awk '{print $9}' bimmel`

rm bimmel
if ($bimstat) then
 xset b 5 400 50 
else
 xset b $vol $pitch $dur
endif

#
#
#
